// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: ondisplay

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_sensorScreen
void ui_sensorScreen_screen_init(void);
void ui_event_sensorScreen( lv_event_t * e);
lv_obj_t *ui_sensorScreen;
lv_obj_t *ui_Container4;
lv_obj_t *ui_lastUpdate;
lv_obj_t *ui_sensorPanel;
lv_obj_t *ui_Image7;
lv_obj_t *ui_Image8;
lv_obj_t *ui_Image9;


// SCREEN: ui_logScreen
void ui_logScreen_screen_init(void);
void ui_event_logScreen( lv_event_t * e);
lv_obj_t *ui_logScreen;
lv_obj_t *ui_Container1;
lv_obj_t *ui_lbStatus;
lv_obj_t *ui_mainPanel;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_sensorScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT  ) {
lv_indev_wait_release(lv_indev_active());
      _ui_screen_change( &ui_logScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_logScreen_screen_init);
}
}
void ui_event_logScreen( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);
if ( event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT  ) {
lv_indev_wait_release(lv_indev_active());
      _ui_screen_change( &ui_sensorScreen, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_sensorScreen_screen_init);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_display_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_sensorScreen_screen_init();
ui_logScreen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_sensorScreen);
}
