// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: ondisplay

#ifndef _ONDISPLAY_UI_H
#define _ONDISPLAY_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_sensorScreen
void ui_sensorScreen_screen_init(void);
void ui_event_sensorScreen( lv_event_t * e);
extern lv_obj_t *ui_sensorScreen;
extern lv_obj_t *ui_Container4;
extern lv_obj_t *ui_lastUpdate;
extern lv_obj_t *ui_sensorPanel;
extern lv_obj_t *ui_Image7;
extern lv_obj_t *ui_Image8;
extern lv_obj_t *ui_Image9;
// SCREEN: ui_logScreen
void ui_logScreen_screen_init(void);
void ui_event_logScreen( lv_event_t * e);
extern lv_obj_t *ui_logScreen;
extern lv_obj_t *ui_Container1;
extern lv_obj_t *ui_lbStatus;
extern lv_obj_t *ui_mainPanel;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_thermometer_png);   // assets/thermometer.png
LV_IMG_DECLARE( ui_img_humidity_png);   // assets/humidity.png
LV_IMG_DECLARE( ui_img_dew_png);   // assets/dew.png


LV_FONT_DECLARE( ui_font_opensans16);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
