// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 9.1.0
// Project name: ondisplay

#include "ui.h"

void ui_sensorScreen_screen_init(void)
{
ui_sensorScreen = lv_obj_create(NULL);
lv_obj_remove_flag( ui_sensorScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_sensorScreen,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_sensorScreen, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

ui_Container4 = lv_obj_create(ui_sensorScreen);
lv_obj_remove_style_all(ui_Container4);
lv_obj_set_height( ui_Container4, 20);
lv_obj_set_width( ui_Container4, lv_pct(100));
lv_obj_set_x( ui_Container4, -76 );
lv_obj_set_y( ui_Container4, -31 );
lv_obj_set_align( ui_Container4, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Container4, lv_color_hex(0xBCBCBC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Container4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_lastUpdate = lv_label_create(ui_Container4);
lv_obj_set_width( ui_lastUpdate, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_lastUpdate, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_lastUpdate, LV_ALIGN_CENTER );
lv_label_set_text(ui_lastUpdate,"00:00:00");

ui_sensorPanel = lv_obj_create(ui_sensorScreen);
lv_obj_remove_style_all(ui_sensorPanel);
lv_obj_set_width( ui_sensorPanel, lv_pct(100));
lv_obj_set_height( ui_sensorPanel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_sensorPanel, LV_ALIGN_BOTTOM_MID );
lv_obj_set_flex_flow(ui_sensorPanel,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_sensorPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_sensorPanel, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_pad_left(ui_sensorPanel, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_sensorPanel, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_sensorPanel, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_sensorPanel, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_sensorPanel, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_sensorPanel, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image7 = lv_image_create(ui_sensorScreen);
lv_image_set_src(ui_Image7, &ui_img_thermometer_png);
lv_obj_set_width( ui_Image7, LV_SIZE_CONTENT);  /// 24
lv_obj_set_height( ui_Image7, LV_SIZE_CONTENT);   /// 24
lv_obj_set_align( ui_Image7, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image7, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_Image7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image8 = lv_image_create(ui_sensorScreen);
lv_image_set_src(ui_Image8, &ui_img_humidity_png);
lv_obj_set_width( ui_Image8, LV_SIZE_CONTENT);  /// 20
lv_obj_set_height( ui_Image8, LV_SIZE_CONTENT);   /// 20
lv_obj_set_align( ui_Image8, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image8, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_Image8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image9 = lv_image_create(ui_sensorScreen);
lv_image_set_src(ui_Image9, &ui_img_dew_png);
lv_obj_set_width( ui_Image9, LV_SIZE_CONTENT);  /// 20
lv_obj_set_height( ui_Image9, LV_SIZE_CONTENT);   /// 20
lv_obj_set_align( ui_Image9, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image9, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_Image9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_add_event_cb(ui_sensorScreen, ui_event_sensorScreen, LV_EVENT_ALL, NULL);

}
